# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
 
- script: dotnet build 'FunctionApp1.sln' --configuration 'Release'
  displayName: 'Build solution'
     
- script: dotnet test 'XUnitTestProject1' --configuration 'Release' --logger trx
  displayName: 'Run unit tests'
 
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
 
- script: dotnet publish 'FunctionApp1/FunctionApp1.csproj' --configuration 'Release' --output '$(Build.ArtifactStagingDirectory)/app'
  displayName: 'Package function app'
 
- task: PublishBuildArtifacts@1
  displayName: 'Publishing app artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
    artifactName: app